#Commands for hub
CMD_GETMASTERINFO = 103
CMD_MASTERINFOINDICATION = 105
CMD_SETPORTCONFIG = 15
CMD_SETCOMMAND = 1
CMD_GETPORTCONFIG = 16
CMD_GETMODE = 14
CMD_DSCOMMAND= 21
CMD_DSCONTENTGET= 22

CMD_DSCONTENTGETINDICATION= 22
CMD_DSCONTENTSETSTART= 24
CMD_DSCONTENTSETSTARTCON= 24
CMD_DSCONTENTSET = 23

CMD_ALREADREQ = 2
CMD_ALREADCON = 9
CMD_ALREADERR = 6
CMD_ALWRITEREQ = 3
CMD_ALWRITECON = 8
CMD_ALWRITEERR = 7
CMD_ALABORTIND = 5
CMD_ALEVENTIND = 4


CMD_READPROCESSDATA = 10
CMD_WRITEPROCESSDATA = 11
CMD_TRANSFERROCESSDATA = 12
CMD_READPROCESSOUTPUTS = 13

CMD_CONNECT = 153
CMD_IDLE = 155
CMD_DISCONNECT = 154

CMD_DEVICEDISCOVERYREQ = 150
CMD_DEVICEDISCOVERYREQCON = 150
CMD_DEVICEDISCOVERYSET = 151
CMD_DEVICEDISCOVERYBLINK = 152

# IO LINK See 1. 
CommunicationType=2

#Confirmation Results
RESULT_SUCCESS=0
RESULT_STATE_CONFLICT=1
RESULT_NOT_SUPPORTED=2
RESULT_SERVICE_PENDING=3
RESULT_WRONG_PARAMETER=4
RESULT_NO_COMMUNICATION=5
RESULT_MIN_CYCLE_TIME=6
RESULT_NO_RESOURCES=7
RESULT_ABORT=8